# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Continuous Integration and Deployment: https://travis-ci.org
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
language: php
php:
  - 5.6
#  - nightly
#
# Parallelizing builds
#
env:
  - TEST_SUITE=unit
#
# build lifecycle
#
before_install:
  - composer --version
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
#  - sudo apt-get install tree
install: 
  - composer --version
  - composer install --prefer-dist
#tree /home/travis -I build -a L 2
before_script:
script:
  - cd app/tests
  - ../../vendor/bin/phpunit --testsuite=$TEST_SUITE --colors
after_success:
after_failure:
after_script:
before_deployment:
deployment:
after_deployment:
#
# cache on success. lifetime?
# 
cache:
  directories:
    - /home/travis/.phpenv/versions/5.6/composer.phar
    - /home/travis/.composer
    # app
    - /home/travis/build/yurii-github/yii2-mylib/vendor
