# 
# Continious Integration by https://travis-ci.org
# 
language: php
php: 5.6
#
# build lifecycle
#
before_install: composer self-update
install:        composer update
before_script:
script:         cd app/tests; phpunit
after_success:
after_failure:
after_script:
before_deployment:
deployment:
after_deployment:
