# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Continuous Integration and Deployment: https://travis-ci.org
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
language: php
php:
  - 5.6
#  - nightly
#
# Parallelizing builds
#
env:
  - TEST_SUITE=unit
#
# build lifecycle
#
before_install:
  - composer self-update
  - sudo apt-get install tree
install:
  - composer install --prefer-dist
before_script:
script:
#  - cd app/tests
#  - ../../vendor/bin/phpunit --testsuite=$TEST_SUITE --colors
after_success:
after_failure:
after_script:
before_deployment:
deployment:
after_deployment:
#
# cache on success. lifetime?
#
cache:
  apt
  directories:
    - /home/travis/.composer
    - vendor
