# 
# Continuous Integration and Deployment: https://travis-ci.org
# 
language: php
php: 5.6
#
# Parallelizing builds
#
env:
  - TEST_SUITE=unit
#
# build lifecycle
#
before_install: composer self-update
install:        composer update
before_script:
script:         cd app/tests; phpunit --testsuite=unit --colors; cd ../..; $? pwd
after_success:
after_failure:
after_script:
before_deployment:
deployment:
after_deployment:
#
# cache on success. life?
#
